### ISSUE TITLE
Traceback (most recent call last)

### ISSUE THREAD

**Issue by panchenglei** [AIGCT/EASYChatGPT#17]
``Traceback (most recent call last):
  File "C:\Users\pcl\Downloads\EASYChatGPT-main\EASYChatGPT-main\app.py", line 1, in <module>
    from bbot import run
  File "C:\Users\pcl\Downloads\EASYChatGPT-main\EASYChatGPT-main\bbot.py", line 1, in <module>
    from revChatGPT.Official import Chatbot
ModuleNotFoundError: No module named 'revChatGPT.Official'

**Comment by skychecker** [comment]
打开bbot.py，把第一行import revChatGPT.Officail改成import revChatGPT.Unoffical

**Comment by shanghaistoneman** [comment]
我修改bbot.py后，再次运行app.py，结果报错：


Traceback (most recent call last):
  File "F:\工具软件\ChatGPT\EASYChatGPT-main\app.py", line 1, in <module>
    from bbot import run
  File "F:\工具软件\ChatGPT\EASYChatGPT-main\bbot.py", line 1, in <module>
    from revChatGPT.Unofficial import Chatbot
  File "C:\Python\lib\site-packages\revChatGPT\Unofficial.py", line 7, in <module>
    import tls_client
ModuleNotFoundError: No module named 'tls_client'


“tls_client”是什么？
