### ISSUE TITLE
运行后提示That model does not exist

### ISSUE THREAD

**Issue by PonsLee** [AIGCT/EASYChatGPT#5]
Traceback (most recent call last):
  File "/Users/pons/File/github/EASYChatGPT-main/app.py", line 5, in <module>
    run()
  File "/Users/pons/File/github/EASYChatGPT-main/bbot.py", line 24, in run
    out = chatbot.ask(input_text)
  File "/usr/local/lib/python3.9/site-packages/revChatGPT/Official.py", line 139, in ask
    completion = self._get_completion(
  File "/usr/local/lib/python3.9/site-packages/revChatGPT/Official.py", line 64, in _get_completion
    return openai.Completion.create(
  File "/usr/local/lib/python3.9/site-packages/openai/api_resources/completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "/usr/local/lib/python3.9/site-packages/openai/api_requestor.py", line 226, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "/usr/local/lib/python3.9/site-packages/openai/api_requestor.py", line 619, in _interpret_response
    self._interpret_response_line(
  File "/usr/local/lib/python3.9/site-packages/openai/api_requestor.py", line 679, in _interpret_response_line
    raise self.handle_error_response(
openai.error.InvalidRequestError: That model does not exist

**Comment by hucc1995** [comment]
Update 2023/02/08: This model has been revoked by OpenAI. We are working towards a new model.
As a temporary workaround, set environment variable export GPT_ENGINE="text-davinci-003" (Costs credit)

**Comment by 563816752** [comment]
+1

**Comment by YZJ2023** [comment]
(EASYChatGPT) root@test3:/data/EASYChatGPT# export GPT_ENGINE="text-davinci-003"
(EASYChatGPT) root@test3:/data/EASYChatGPT# python app.py
遇到报错优先考虑重新运行 

你的 输入: 
hello
Traceback (most recent call last):
  File "app.py", line 7, in <module>
    run()
  File "/data/EASYChatGPT/bbot.py", line 24, in run
    out = chatbot.ask(input_text)
  File "/home/user/anaconda3/envs/EASYChatGPT/lib/python3.7/site-packages/revChatGPT/Official.py", line 50, in ask
    stop=["\n\n\n"],
  File "/home/user/anaconda3/envs/EASYChatGPT/lib/python3.7/site-packages/openai/api_resources/completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "/home/user/anaconda3/envs/EASYChatGPT/lib/python3.7/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 160, in create
    request_timeout=request_timeout,
  File "/home/user/anaconda3/envs/EASYChatGPT/lib/python3.7/site-packages/openai/api_requestor.py", line 226, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "/home/user/anaconda3/envs/EASYChatGPT/lib/python3.7/site-packages/openai/api_requestor.py", line 623, in _interpret_response
    stream=False,
  File "/home/user/anaconda3/envs/EASYChatGPT/lib/python3.7/site-packages/openai/api_requestor.py", line 680, in _interpret_response_line
    rbody, rcode, resp.data, rheaders, stream_error=stream_error
openai.error.InvalidRequestError: That model does not exist

**Comment by PonsLee** [comment]
> 



> (EASYChatGPT) root@test3:/data/EASYChatGPT# export GPT_ENGINE="text-davinci-003" (EASYChatGPT) root@test3:/data/EASYChatGPT# python app.py 遇到报错优先考虑重新运行
> 
> 你的 输入: hello Traceback (most recent call last): File "app.py", line 7, in run() File "/data/EASYChatGPT/bbot.py", line 24, in run out = chatbot.ask(input_text) File "/home/user/anaconda3/envs/EASYChatGPT/lib/python3.7/site-packages/revChatGPT/Official.py", line 50, in ask stop=["\n\n\n"], File "/home/user/anaconda3/envs/EASYChatGPT/lib/python3.7/site-packages/openai/api_resources/completion.py", line 25, in create return super().create(*args, **kwargs) File "/home/user/anaconda3/envs/EASYChatGPT/lib/python3.7/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 160, in create request_timeout=request_timeout, File "/home/user/anaconda3/envs/EASYChatGPT/lib/python3.7/site-packages/openai/api_requestor.py", line 226, in request resp, got_stream = self._interpret_response(result, stream) File "/home/user/anaconda3/envs/EASYChatGPT/lib/python3.7/site-packages/openai/api_requestor.py", line 623, in _interpret_response stream=False, File "/home/user/anaconda3/envs/EASYChatGPT/lib/python3.7/site-packages/openai/api_requestor.py", line 680, in _interpret_response_line rbody, rcode, resp.data, rheaders, stream_error=stream_error openai.error.InvalidRequestError: That model does not exist

try 
export GPT_ENGINE=text-davinci-003
and
pip3 install tiktoken

**Comment by YZJ2023** [comment]
> > 
> 
> > (EASYChatGPT) root@test3:/data/EASYChatGPT# export GPT_ENGINE="text-davinci-003" (EASYChatGPT) root@test3:/data/EASYChatGPT# python app.py 遇到报错优先考虑重新运行
> > 你的 输入: hello Traceback (most recent call last): File "app.py", line 7, in run() File "/data/EASYChatGPT/bbot.py", line 24, in run out = chatbot.ask(input_text) File "/home/user/anaconda3/envs/EASYChatGPT/lib/python3.7/site-packages/revChatGPT/Official.py", line 50, in ask stop=["\n\n\n"], File "/home/user/anaconda3/envs/EASYChatGPT/lib/python3.7/site-packages/openai/api_resources/completion.py", line 25, in create return super().create(*args, **kwargs) File "/home/user/anaconda3/envs/EASYChatGPT/lib/python3.7/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 160, in create request_timeout=request_timeout, File "/home/user/anaconda3/envs/EASYChatGPT/lib/python3.7/site-packages/openai/api_requestor.py", line 226, in request resp, got_stream = self._interpret_response(result, stream) File "/home/user/anaconda3/envs/EASYChatGPT/lib/python3.7/site-packages/openai/api_requestor.py", line 623, in _interpret_response stream=False, File "/home/user/anaconda3/envs/EASYChatGPT/lib/python3.7/site-packages/openai/api_requestor.py", line 680, in _interpret_response_line rbody, rcode, resp.data, rheaders, stream_error=stream_error openai.error.InvalidRequestError: That model does not exist
> 
> try export GPT_ENGINE=text-davinci-003 and pip3 install tiktoken

I solved this problem by edit "/python3.7/site-packages/revChatGPT/Official.py"
![image](https://user-images.githubusercontent.com/121933144/218045739-a35feb1d-2501-4173-bdbb-1ab660802b6d.png)
